/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./../src/components/base-components/base-button/index.vue')['default']
    BaseCheckbox: typeof import('./../src/components/base-components/base-checkbox/index.vue')['default']
    BaseContainer: typeof import('./../src/components/base-components/base-container/index.vue')['default']
    BaseImage: typeof import('./../src/components/base-components/base-image/index.vue')['default']
    BaseInput: typeof import('./../src/components/base-components/base-input/index.vue')['default']
    BaseInsComError: typeof import('./../src/components/base-components/base-ins-com-error/index.vue')['default']
    BaseInsComLoading: typeof import('./../src/components/base-components/base-ins-com-loading/index.vue')['default']
    BaseRadio: typeof import('./../src/components/base-components/base-radio/index.vue')['default']
    BaseRadioGroup: typeof import('./../src/components/base-components/base-radio-group/index.vue')['default']
    BaseSelect: typeof import('./../src/components/base-components/base-select/index.vue')['default']
    BaseSwitch: typeof import('./../src/components/base-components/base-switch/index.vue')['default']
    BaseText: typeof import('./../src/components/base-components/base-text/index.vue')['default']
    BaseTextarea: typeof import('./../src/components/base-components/base-textarea/index.vue')['default']
    ConfigPageContainer: typeof import('./../src/components/dynamic-renderer/config-page-container/index.vue')['default']
    DynamicRenderer: typeof import('./../src/components/dynamic-renderer/index.vue')['default']
    DynamicUiRenderer: typeof import('./../src/components/dynamic-renderer/dynamic-ui-renderer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
